name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      env:
        EMAIL: ${{ secrets.EMAIL }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.3

    - name: Compile
      run: make

    - name: Set git safe directory
      run: git config --global --add safe.directory /__w/Awesome-CV/Awesome-CV

    - name: Commit & Push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: pdfs/*.pdf --force
        message: Update pdfs
        github_token: ${{ secrets.GITHUB_TOKEN }}
